(function(){
  'use strict';
  function boot(){
    if(document.getElementById('dionuel-phase1-store')) return;
    var root=document.createElement('section');root.id='dionuel-phase1-store';
    root.innerHTML=`<div class="sf-shell"><header class="sf-top"><div class="sf-brand">DIONUEL<small>Alfaiataria & Atelier · Luanda</small></div><div class="sf-actions"><button class="sf-btn" id="sf-login">Área do cliente / equipa</button><button class="sf-btn primary" id="sf-whatsapp">Falar no WhatsApp</button></div></header><section class="sf-hero"><div><span class="sf-kicker">Feito à medida · Luanda</span><h1>Elegância que começa em si.</h1><p>Peças feitas à medida, acabamento cuidado e acompanhamento personalizado — do primeiro pedido à entrega.</p><div class="sf-actions" style="margin-top:22px"><button class="sf-btn primary" id="sf-quote">Solicitar uma peça</button><button class="sf-btn" id="sf-services-btn">Ver serviços</button></div></div><div class="sf-hero-card"><div><span class="sf-kicker">DIONUEL</span><strong>Seu estilo.<br>Seu corte.<br>Sua medida.</strong></div></div></section><section class="sf-section"><div class="sf-section-head"><h2>Explore a coleção</h2><span id="sf-count">A carregar...</span></div><div class="sf-cats" id="sf-cats"><button class="sf-cat active" data-cat="all">Todos</button><button class="sf-cat" data-cat="fato">Fatos</button><button class="sf-cat" data-cat="safari">Safari</button><button class="sf-cat" data-cat="camisa">Camisas</button><button class="sf-cat" data-cat="vestido">Vestidos</button><button class="sf-cat" data-cat="africano">Moda Africana</button></div><div class="sf-grid" id="sf-grid"><div class="sf-loading">A carregar peças...</div></div></section><section class="sf-section" id="sf-services"><div class="sf-section-head"><h2>Serviços DIONUEL</h2><span>Do desenho à entrega</span></div><div class="sf-services"><div class="sf-service"><b>Alfaiataria sob medida</b><span>Fatos, blazers, camisas e peças construídas de acordo com as suas medidas e preferência.</span></div><div class="sf-service"><b>Noivos & cerimónia</b><span>Consultoria de estilo e confeção para momentos em que cada detalhe importa.</span></div><div class="sf-service"><b>Ajustes & transformação</b><span>Correções, ajustes e transformação de peças com acabamento profissional.</span></div></div></section><footer class="sf-footer"><span>DIONUEL | Alfaiataria & Atelier</span><span>Luanda, Angola · WhatsApp 932 020 351</span></footer></div>`;
    document.body.appendChild(root);
    var wa='https://wa.me/244932020351?text='+encodeURIComponent('Olá DIONUEL, gostaria de solicitar uma peça sob medida.');
    document.getElementById('sf-whatsapp').onclick=function(){location.href=wa};
    document.getElementById('sf-quote').onclick=function(){location.href=wa};
    document.getElementById('sf-login').onclick=function(){root.remove();window.scrollTo(0,0)};
    document.getElementById('sf-services-btn').onclick=function(){document.getElementById('sf-services').scrollIntoView({behavior:'smooth'})};
    var grid=document.getElementById('sf-grid'),count=document.getElementById('sf-count'),active='all',items=[];
    function render(){var list=active==='all'?items:items.filter(function(p){var t=((p.categoria||p.tipo||p.nome||'')+'').toLowerCase();return t.indexOf(active)>=0});count.textContent=list.length+' peça'+(list.length===1?'':'s');if(!list.length){grid.innerHTML='<div class="sf-loading">Em breve teremos peças nesta categoria.</div>';return}grid.innerHTML=list.slice(0,12).map(function(p){var name=p.nome||p.name||p.titulo||'Peça DIONUEL';var desc=p.descricao||p.description||'Confeção personalizada DIONUEL.';var img=p.imagem_url||p.imagem||p.foto_url||p.image_url||'';return '<article class="sf-product"><div class="sf-media">'+(img?'<img loading="lazy" src="'+img.replace(/"/g,'&quot;')+'" alt="'+name.replace(/"/g,'&quot;')+'">':'DIONUEL')+'</div><div class="sf-info"><small>Feito à medida</small><h3>'+name+'</h3><p>'+desc+'</p></div><button class="sf-btn primary sf-product-btn">Solicitar</button></article>'}).join('');Array.from(grid.querySelectorAll('.sf-product-btn')).forEach(function(b){b.onclick=function(){location.href=wa}})}
    Array.from(document.querySelectorAll('.sf-cat')).forEach(function(b){b.onclick=function(){active=b.dataset.cat;document.querySelectorAll('.sf-cat').forEach(function(x){x.classList.remove('active')});b.classList.add('active');render()}});
    function load(){if(window.supabase&&window.supabase.from){window.supabase.from('produtos').select('*').limit(24).then(function(r){items=r.data||[];render()}).catch(function(){items=[];render()})}else{setTimeout(load,500)}}load();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
